### ISSUE TITLE
BLAST Database error: Error pre-fetching sequence data

### ISSUE THREAD

**Issue by ramadatta** [tseemann/abricate#164]
Hi,

I have installed abricate using conda. When I run the command:

```bash
$ abricate test.fasta
Using nucl database ncbi:  5386 sequences -  2021-Mar-27
#FILE	SEQUENCE	START	END	STRAND	GENE	COVERAGE	COVERAGE_MAP	GAPS	%COVERAGE	%IDENTITY	DATABASE	ACCESSION	PRODUCT	RESISTANCE
Processing: test.fasta
BLAST Database error: Error pre-fetching sequence data 
Found 0 genes in test.fasta
Tip: it's important to realise abricate uses DNA matching, not AA.
Done.
```
Can kindly request help on how to resolve this. Many thanks in advance.

**Comment by lireo** [comment]
Hi 

I have same problem with a fresh abricate install with conda. 
Also, appreciate any help I can get

**Comment by andersgs** [comment]
Can you confirm the blast version? Thank you.

**Comment by lireo** [comment]
My blast version is :
`blastn: 2.9.0+
 Package: blast 2.9.0, build Sep 26 2019 23:31:55`

Thank you for your help

**Comment by andersgs** [comment]
The issue comes down to a change in the blast DB format. NCBI updated their default DB format from V4 to V5. 

blast 2.9 was the last version that read (and wrote) V4 by default (optionally it would read/write V5). From version 2.11 (I believe) V4 support is dropped all together. 

The current blast DB shipped with abricate is V5. 

You have two options:

1. Run `abricate --setupdb` which will re-create all the blast DBs. Since you have blast 2.9, it will do them in V4. 

2. Upgrade to blast v2.10 or above: `conda install -c bioconda blast=2.11`

I will work on the conda recipe to update the minimum requirements.

**Comment by lireo** [comment]
I can't update blast, there are to many conflicts but I succeed with your first solution `abricate --setupdb`

Thank you very much

**Comment by andersgs** [comment]
I will close this issue. If needed, please re-open.

**Comment by ramadatta** [comment]
`abricate --setupdb` resolved the issue. Thank you very much!

**Comment by swati7024** [comment]
hey..
Even after updating the blast and also run the command abricate --setupdb my problem is not solved showing the same error blastN database not found...
Also when I am creating the vfdb database it is extracting sequences in duplex, triplex and many more times...
Please help..
Thank you
