### ISSUE TITLE
conda installs an older version of abricate

### ISSUE THREAD

**Issue by kaanb93** [tseemann/abricate#167]
Hello,

I have just tried to install abricate with conda as shown in the page:

`conda install -c conda-forge -c bioconda -c defaults abricate
`

This command installed v0.8 whereas cloning from github installed the last version as today, v1.0.1.

Since I got it right with installing from the source, I don't have any problems; but I think conda installation needs to be checked.

Thank you very much for this great tool!

**Comment by andersgs** [comment]
This is a known thing that can happen because of the solver Conda uses in the background to figure out what version to install (you can check https://github.com/conda/conda/issues/2011 for some background).

So, I would usually recommend people install specific (or fuzzy, close to the version) versions whenever you can:

`conda install -c conda-forge -c bioconda -c defaults abricate=1.0` --- Note that I used a single `=`, which means do a fuzzy match, if you use `==` then it will be a specific match.

That way you will be certain of what is installed, and if there are any inconsistencies in your environment they will crop up.

Checkout the Conda Cheatsheet to see how else you can specify versions: https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf
