### ISSUE TITLE
run with multiple database

### ISSUE THREAD

**Issue by lcerdeira** [tseemann/abricate#50]
Is it possible to run with multiple databases? I tried to run with all the database using comma to separate the databases , but did not work.

**Comment by tseemann** [comment]
No, that is not supported.

However, if you go into `abricate/db/abricate` you will see a `README` file which you can run to make a combined non-redundant AMR database (it will ignore VFDB etc, but you can customise).

Then just use `--db abricate`

Alternatively make your own database:
https://github.com/tseemann/abricate#making-your-own-database

**Comment by felipelira** [comment]
Sorry to answer in this issue but I tried to format a database using the example 
"makeblastdb -in sequences -title tinyamr -dbtype nucl -parse_seqids -hash_index"

It doesn't work because it is missing the option to create a log file. The correct line would be: 
"makeblastdb -in sequences -title tinyamr -dbtype nucl -parse_seqids -hash_index -logfile <your log file>"
